version: '3.4'

services:
  gatsby:
    command: gatsby develop --host 0.0.0.0 --port 8000
    build:
      context: ../
      dockerfile: ./ops/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../site:/application
    working_dir: /application
